name: get

on:
  schedule:
    - cron: '25 8 * * *'
    
  workflow_dispatch:


jobs:
  get:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install aiohttp
          #pip install selenium requests futures opencv-python eventlet
          pip install selenium requests futures eventlet
          sudo apt-get install ffmpeg


      - name: Run itv
        run: python ${{ github.workspace }}/pytemp/get.py

      - name: Run itvtest
        run: python ${{ github.workspace }}/pytemp/testhd
        

      - name: 提交更改
        run: |
          git config --local user.email "6fybq3a5@nqmo.com"
          git config --local user.name "o1il"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
 
